Workaround mixed OpenSAML versions
IDP-1217 introduced support for RequestedAttribute which triggers :

 java.lang.NoClassDefFoundError:
 org/opensaml/saml/ext/reqattr/RequestedAttributes

because the test (Maven Surefire) classpath sometimes has mixed (3.3 and
3.4) versions of OpenSAML.

See also OSJ-242